/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueueAddRouteImport } from './routes/queue.add'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueAddRoute = QueueAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => QueueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/queue': typeof QueueRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRoute
  '/queue/add': typeof QueueAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/queue': typeof QueueRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRoute
  '/queue/add': typeof QueueAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/queue': typeof QueueRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRoute
  '/queue/add': typeof QueueAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/queue'
    | '/settings'
    | '/setup'
    | '/signup'
    | '/superadmin'
    | '/queue/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/queue'
    | '/settings'
    | '/setup'
    | '/signup'
    | '/superadmin'
    | '/queue/add'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/queue'
    | '/settings'
    | '/setup'
    | '/signup'
    | '/superadmin'
    | '/queue/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  QueueRoute: typeof QueueRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  SuperadminRoute: typeof SuperadminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/add': {
      id: '/queue/add'
      path: '/add'
      fullPath: '/queue/add'
      preLoaderRoute: typeof QueueAddRouteImport
      parentRoute: typeof QueueRoute
    }
  }
}

interface QueueRouteChildren {
  QueueAddRoute: typeof QueueAddRoute
}

const QueueRouteChildren: QueueRouteChildren = {
  QueueAddRoute: QueueAddRoute,
}

const QueueRouteWithChildren = QueueRoute._addFileChildren(QueueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  QueueRoute: QueueRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  SuperadminRoute: SuperadminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
